version: 1.0.{build}
branches:
  only:
  - master
build:
  verbosity: minimal
image: Visual Studio 2017
environment:
  DOCKER_USER:
    secure: AV71NGW/I1JvBlK3ajVvTw==
  DOCKER_PASS:
    secure: mwwthyjc4HXdTuMKHKbmekkNuFnb0JOKmsHhundz+sc=
install:
  - docker version
build_script:
  - ps: .\build.ps1
test_script:
  - ps: .\test.ps1
deploy_script:
  - ps: .\deploy.ps1